package core.model.match;

import core.model.match.MatchEvent.MatchEventID;
import core.model.match.MatchEvent.MatchPartId;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.Arrays;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.params.provider.Arguments.of;

class MatchEventIDTest {

    private static Stream<Arguments> MatchEventID_fromMatchEventID() {
        return Stream.of(
            of(19, MatchEventID.PLAYERS_ENTER_THE_FIELD),
            of(20, MatchEventID.TACTICAL_DISPOSITION),
            of(21, MatchEventID.PLAYER_NAMES_IN_LINEUP),
            of(22, MatchEventID.PLAYERS_FROM_NEIGHBORHOOD_USED),
            of(23, MatchEventID.SAME_FORMATION_BOTH_TEAMS),
            of(24, MatchEventID.TEAM_FORMATIONS_DIFFERENT),
            of(25, MatchEventID.REGIONAL_DERBY),
            of(26, MatchEventID.NEUTRAL_GROUND),
            of(27, MatchEventID.AWAY_IS_ACTUALLY_HOME),
            of(28, MatchEventID.WALKOVER_LINEUP_USED),
            of(30, MatchEventID.SPECTATORS_OR_VENUE_RAIN),
            of(31, MatchEventID.SPECTATORS_OR_VENUE_CLOUDY),
            of(32, MatchEventID.SPECTATORS_OR_VENUE_FAIR_WEATHER),
            of(33, MatchEventID.SPECTATORS_OR_VENUE_SUNNY),
            of(35, MatchEventID.ARENA_EXTENDED_WITH_TEMPORARY_SEATS),
            of(36, MatchEventID.ONLY_VENUE_RAIN),
            of(37, MatchEventID.ONLY_VENUE_CLOUDY),
            of(38, MatchEventID.ONLY_VENUE_FAIR_WEATHER),
            of(39, MatchEventID.ONLY_VENUE_SUNNY),
            of(40, MatchEventID.DOMINATED),
            of(41, MatchEventID.BEST_PLAYER),
            of(42, MatchEventID.WORST_PLAYER),
            of(45, MatchEventID.HALF_TIME_RESULTS),
            of(46, MatchEventID.HATTRICK_COMMENT),
            of(47, MatchEventID.NO_TEAM_DOMINATED),
            of(55, MatchEventID.PENALTY_CONTEST_GOAL_BY_TECHNICAL_NO_NERVES),
            of(56, MatchEventID.PENALTY_CONTEST_GOAL_NO_NERVES),
            of(57, MatchEventID.PENALTY_CONTEST_GOAL_IN_SPITE_OF_NERVES),
            of(58, MatchEventID.PENALTY_CONTEST_NO_GOAL_BECAUSE_OF_NERVES),
            of(59, MatchEventID.PENALTY_CONTEST_NO_GOAL_IN_SPITE_OF_NO_NERVES),
            of(60, MatchEventID.UNDERESTIMATION),
            of(61, MatchEventID.ORGANIZATION_BREAKS),
            of(62, MatchEventID.WITHDRAW),
            of(63, MatchEventID.REMOVE_UNDERESTIMATION_AT_PAUSE),
            of(64, MatchEventID.REORGANIZE),
            of(65, MatchEventID.NERVES_IN_IMPORTANT_THRILLING_GAME),
            of(66, MatchEventID.REMOVE_UNDERESTIMATION_AT_PAUSE_GOALDIFF_IS_0),
            of(67, MatchEventID.REMOVE_UNDERESTIMATION_AT_PAUSE_GOALDIFF_IS_1),
            of(68, MatchEventID.SUCCESSFUL_PRESSING),
            of(69, MatchEventID.REMOVE_UNDERESTIMATION),
            of(70, MatchEventID.EXTENSION),
            of(71, MatchEventID.PENALTY_CONTEST_AFTER_EXTENSION),
            of(72, MatchEventID.EXTENSION_DECIDED),
            of(73, MatchEventID.AFTER_22_PENALTIES_TOSSING_COIN),
            of(75, MatchEventID.ADDED_TIME),
            of(76, MatchEventID.NO_ADDED_TIME),
            of(80, MatchEventID.NEW_CAPTAIN),
            of(81, MatchEventID.NEW_SET_PIECES_TAKER),
            of(90, MatchEventID.INJURED_BUT_KEEPS_PLAYING),
            of(91, MatchEventID.MODERATELY_INJURED_LEAVES_FIELD),
            of(92, MatchEventID.BADLY_INJURED_LEAVES_FIELD),
            of(93, MatchEventID.INJURED_AND_NO_REPLACEMENT_EXISTED),
            of(94, MatchEventID.INJURED_AFTER_FOUL_BUT_CONTINUES),
            of(95, MatchEventID.INJURED_AFTER_FOUL_AND_EXITS),
            of(96, MatchEventID.INJURED_AFTER_FOUL_AND_NO_REPLACEMENT_EXISTED),
            of(97, MatchEventID.KEEPER_INJURED_FIELD_PLAYER_HAS_TO_TAKE_HIS_PLACE),
            of(100, MatchEventID.REDUCING_GOAL_HOME_TEAM_FREE_KICK),
            of(101, MatchEventID.REDUCING_GOAL_HOME_TEAM_MIDDLE),
            of(102, MatchEventID.REDUCING_GOAL_HOME_TEAM_LEFT_WING),
            of(103, MatchEventID.REDUCING_GOAL_HOME_TEAM_RIGHT_WING),
            of(104, MatchEventID.REDUCING_GOAL_HOME_TEAM_PENALTY_KICK_NORMAL),
            of(105, MatchEventID.SE_GOAL_UNPREDICTABLE_LONG_PASS),
            of(106, MatchEventID.SE_GOAL_UNPREDICTABLE_SCORES_ON_HIS_OWN),
            of(107, MatchEventID.GOAL_LONG_SHOT_NO_TACTIC),
            of(108, MatchEventID.SE_GOAL_UNPREDICTABLE_SPECIAL_ACTION),
            of(109, MatchEventID.SE_GOAL_UNPREDICTABLE_MISTAKE),
            of(110, MatchEventID.EQUALIZER_GOAL_HOME_TEAM_FREE_KICK),
            of(111, MatchEventID.EQUALIZER_GOAL_HOME_TEAM_MIDDLE),
            of(112, MatchEventID.EQUALIZER_GOAL_HOME_TEAM_LEFT_WING),
            of(113, MatchEventID.EQUALIZER_GOAL_HOME_TEAM_RIGHT_WING),
            of(114, MatchEventID.EQUALIZER_GOAL_HOME_TEAM_PENALTY_KICK_NORMAL),
            of(115, MatchEventID.SE_QUICK_SCORES_AFTER_RUSH),
            of(116, MatchEventID.SE_QUICK_RUSHES_PASSES_AND_RECEIVER_SCORES),
            of(117, MatchEventID.SE_TIRED_DEFENDER_MISTAKE_STRIKER_SCORES),
            of(118, MatchEventID.SE_GOAL_CORNER_TO_ANYONE),
            of(119, MatchEventID.SE_GOAL_CORNER_HEAD_SPECIALIST),
            of(120, MatchEventID.GOAL_TO_TAKE_LEAD_HOME_TEAM_FREE_KICK),
            of(121, MatchEventID.GOAL_TO_TAKE_LEAD_HOME_TEAM_MIDDLE),
            of(122, MatchEventID.GOAL_TO_TAKE_LEAD_HOME_TEAM_LEFT_WING),
            of(123, MatchEventID.GOAL_TO_TAKE_LEAD_HOME_TEAM_RIGHT_WING),
            of(124, MatchEventID.GOAL_TO_TAKE_LEAD_HOME_TEAM_PENALTY_KICK_NORMAL),
            of(125, MatchEventID.SE_GOAL_UNPREDICTABLE_OWN_GOAL),
            of(130, MatchEventID.INCREASE_GOAL_HOME_TEAM_FREE_KICK),
            of(131, MatchEventID.INCREASE_GOAL_HOME_TEAM_MIDDLE),
            of(132, MatchEventID.INCREASE_GOAL_HOME_TEAM_LEFT_WING),
            of(133, MatchEventID.INCREASE_GOAL_HOME_TEAM_RIGHT_WING),
            of(134, MatchEventID.INCREASE_GOAL_HOME_TEAM_PENALTY_KICK_NORMAL),
            of(135, MatchEventID.SE_EXPERIENCED_FORWARD_SCORES),
            of(136, MatchEventID.SE_INEXPERIENCED_DEFENDER_CAUSES_GOAL),
            of(137, MatchEventID.SE_WINGER_TO_HEAD_SPEC_SCORES),
            of(138, MatchEventID.SE_WINGER_TO_ANYONE_SCORES),
            of(139, MatchEventID.SE_TECHNICAL_GOES_AROUND_HEAD_PLAYER),
            of(140, MatchEventID.COUNTER_ATTACK_GOAL_FREE_KICK),
            of(141, MatchEventID.COUNTER_ATTACK_GOAL_MIDDLE),
            of(142, MatchEventID.COUNTER_ATTACK_GOAL_LEFT),
            of(143, MatchEventID.COUNTER_ATTACK_GOAL_RIGHT),
            of(150, MatchEventID.REDUCING_GOAL_AWAY_TEAM_FREE_KICK),
            of(151, MatchEventID.REDUCING_GOAL_AWAY_TEAM_MIDDLE),
            of(152, MatchEventID.REDUCING_GOAL_AWAY_TEAM_LEFT_WING),
            of(153, MatchEventID.REDUCING_GOAL_AWAY_TEAM_RIGHT_WING),
            of(154, MatchEventID.REDUCING_GOAL_AWAY_TEAM_PENALTY_KICK_NORMAL),
            of(160, MatchEventID.EQUALIZER_GOAL_AWAY_TEAM_FREE_KICK),
            of(161, MatchEventID.EQUALIZER_GOAL_AWAY_TEAM_MIDDLE),
            of(162, MatchEventID.EQUALIZER_GOAL_AWAY_TEAM_LEFT_WING),
            of(163, MatchEventID.EQUALIZER_GOAL_AWAY_TEAM_RIGHT_WING),
            of(164, MatchEventID.EQUALIZER_GOAL_AWAY_TEAM_PENALTY_KICK_NORMAL),
            of(170, MatchEventID.GOAL_TO_TAKE_LEAD_AWAY_TEAM_FREE_KICK),
            of(171, MatchEventID.GOAL_TO_TAKE_LEAD_AWAY_TEAM_MIDDLE),
            of(172, MatchEventID.GOAL_TO_TAKE_LEAD_AWAY_TEAM_LEFT_WING),
            of(173, MatchEventID.GOAL_TO_TAKE_LEAD_AWAY_TEAM_RIGHT_WING),
            of(174, MatchEventID.GOAL_TO_TAKE_LEAD_AWAY_TEAM_PENALTY_KICK_NORMAL),
            of(180, MatchEventID.INCREASE_GOAL_AWAY_TEAM_FREE_KICK),
            of(181, MatchEventID.INCREASE_GOAL_AWAY_TEAM_MIDDLE),
            of(182, MatchEventID.INCREASE_GOAL_AWAY_TEAM_LEFT_WING),
            of(183, MatchEventID.INCREASE_GOAL_AWAY_TEAM_RIGHT_WING),
            of(184, MatchEventID.INCREASE_GOAL_AWAY_TEAM_PENALTY_KICK_NORMAL),
            of(185, MatchEventID.GOAL_INDIRECT_FREE_KICK),
            of(186, MatchEventID.COUNTER_ATTACK_GOAL_INDIRECT_FREE_KICK),
            of(187, MatchEventID.GOAL_LONG_SHOT),
            of(190, MatchEventID.SE_GOAL_POWERFUL_NORMAL_FORWARD_GENERATES_EXTRA_CHANCE),
            of(200, MatchEventID.NO_REDUCING_GOAL_HOME_TEAM_FREE_KICK),
            of(201, MatchEventID.NO_REDUCING_GOAL_HOME_TEAM_MIDDLE),
            of(202, MatchEventID.NO_REDUCING_GOAL_HOME_TEAM_LEFT_WING),
            of(203, MatchEventID.NO_REDUCING_GOAL_HOME_TEAM_RIGHT_WING),
            of(204, MatchEventID.NO_REDUCING_GOAL_HOME_TEAM_PENALTY_KICK_NORMAL),
            of(205, MatchEventID.SE_NO_GOAL_UNPREDICTABLE_LONG_PASS),
            of(206, MatchEventID.SE_NO_GOAL_UNPREDICTABLE_ALMOST_SCORES),
            of(207, MatchEventID.NO_GOAL_LONG_SHOT_NO_TACTIC),
            of(208, MatchEventID.SE_NO_GOAL_UNPREDICTABLE_SPECIAL_ACTION),
            of(209, MatchEventID.SE_NO_GOAL_UNPREDICTABLE_MISTAKE),
            of(210, MatchEventID.NO_EQUALIZER_GOAL_HOME_TEAM_FREE_KICK),
            of(211, MatchEventID.NO_EQUALIZER_GOAL_HOME_TEAM_MIDDLE),
            of(212, MatchEventID.NO_EQUALIZER_GOAL_HOME_TEAM_LEFT_WING),
            of(213, MatchEventID.NO_EQUALIZER_GOAL_HOME_TEAM_RIGHT_WING),
            of(214, MatchEventID.NO_EQUALIZER_GOAL_HOME_TEAM_PENALTY_KICK_NORMAL),
            of(215, MatchEventID.SE_SPEEDY_MISSES_AFTER_RUSH),
            of(216, MatchEventID.SE_QUICK_RUSHES_PASSES_BUT_RECEIVER_FAILS),
            of(217, MatchEventID.SE_TIRED_DEFENDER_MISTAKE_BUT_NO_GOAL),
            of(218, MatchEventID.SE_NO_GOAL_CORNER_TO_ANYONE),
            of(219, MatchEventID.SE_NO_GOAL_CORNER_HEAD_SPECIALIST),
            of(220, MatchEventID.NO_GOAL_TO_TAKE_LEAD_HOME_TEAM_FREE_KICK),
            of(221, MatchEventID.NO_GOAL_TO_TAKE_LEAD_HOME_TEAM_MIDDLE),
            of(222, MatchEventID.NO_GOAL_TO_TAKE_LEAD_HOME_TEAM_LEFT_WING),
            of(223, MatchEventID.NO_GOAL_TO_TAKE_LEAD_HOME_TEAM_RIGHT_WING),
            of(224, MatchEventID.NO_GOAL_TO_TAKE_LEAD_HOME_TEAM_PENALTY_KICK_NORMAL),
            of(225, MatchEventID.SE_NO_GOAL_UNPREDICTABLE_OWN_GOAL_ALMOST),
            of(230, MatchEventID.NO_INCREASE_GOAL_HOME_TEAM_FREE_KICK),
            of(231, MatchEventID.NO_INCREASE_GOAL_HOME_TEAM_MIDDLE),
            of(232, MatchEventID.NO_INCREASE_GOAL_HOME_TEAM_LEFT_WING),
            of(233, MatchEventID.NO_INCREASE_GOAL_HOME_TEAM_RIGHT_WING),
            of(234, MatchEventID.NO_INCREASE_GOAL_HOME_TEAM_PENALTY_KICK_NORMAL),
            of(235, MatchEventID.SE_EXPERIENCED_FORWARD_FAILS_TO_SCORE),
            of(236, MatchEventID.SE_INEXPERIENCED_DEFENDER_ALMOST_CAUSES_GOAL),
            of(237, MatchEventID.SE_WINGER_TO_SOMEONE_NO_GOAL),
            of(239, MatchEventID.SE_TECHNICAL_GOES_AROUND_HEAD_PLAYER_NO_GOAL),
            of(240, MatchEventID.COUNTER_ATTACK_NO_GOAL_FREE_KICK),
            of(241, MatchEventID.COUNTER_ATTACK_NO_GOAL_MIDDLE),
            of(242, MatchEventID.COUNTER_ATTACK_NO_GOAL_LEFT),
            of(243, MatchEventID.COUNTER_ATTACK_NO_GOAL_RIGHT),
            of(250, MatchEventID.NO_REDUCING_GOAL_AWAY_TEAM_FREE_KICK),
            of(251, MatchEventID.NO_REDUCING_GOAL_AWAY_TEAM_MIDDLE),
            of(252, MatchEventID.NO_REDUCING_GOAL_AWAY_TEAM_LEFT_WING),
            of(253, MatchEventID.NO_REDUCING_GOAL_AWAY_TEAM_RIGHT_WING),
            of(254, MatchEventID.NO_REDUCING_GOAL_AWAY_TEAM_PENALTY_KICK_NORMAL),
            of(260, MatchEventID.NO_EQUALIZER_GOAL_AWAY_TEAM_FREE_KICK),
            of(261, MatchEventID.NO_EQUALIZER_GOAL_AWAY_TEAM_MIDDLE),
            of(262, MatchEventID.NO_EQUALIZER_GOAL_AWAY_TEAM_LEFT_WING),
            of(263, MatchEventID.NO_EQUALIZER_GOAL_AWAY_TEAM_RIGHT_WING),
            of(264, MatchEventID.NO_EQUALIZER_GOAL_AWAY_TEAM_PENALTY_KICK_NORMAL),
            of(270, MatchEventID.NO_GOAL_TO_TAKE_LEAD_AWAY_TEAM_FREE_KICK),
            of(271, MatchEventID.NO_GOAL_TO_TAKE_LEAD_AWAY_TEAM_MIDDLE),
            of(272, MatchEventID.NO_GOAL_TO_TAKE_LEAD_AWAY_TEAM_LEFT_WING),
            of(273, MatchEventID.NO_GOAL_TO_TAKE_LEAD_AWAY_TEAM_RIGHT_WING),
            of(274, MatchEventID.NO_GOAL_TO_TAKE_LEAD_AWAY_TEAM_PENALTY_KICK_NORMAL),
            of(280, MatchEventID.NO_INCREASE_GOAL_AWAY_TEAM_FREE_KICK),
            of(281, MatchEventID.NO_INCREASE_GOAL_AWAY_TEAM_MIDDLE),
            of(282, MatchEventID.NO_INCREASE_GOAL_AWAY_TEAM_LEFT_WING),
            of(283, MatchEventID.NO_INCREASE_GOAL_AWAY_TEAM_RIGHT_WING),
            of(284, MatchEventID.NO_INCREASE_GOAL_AWAY_TEAM_PENALTY_KICK_NORMAL),
            of(285, MatchEventID.NO_GOAL_INDIRECT_FREE_KICK),
            of(286, MatchEventID.COUNTER_ATTACK_NO_GOAL_INDIRECT_FREE_KICK),
            of(287, MatchEventID.NO_GOAL_LONG_SHOT),
            of(288, MatchEventID.NO_GOAL_LONG_SHOT_DEFENDED),
            of(289, MatchEventID.SE_QUICK_RUSHES_STOPPED_BY_QUICK_DEFENDER),
            of(290, MatchEventID.SE_NO_GOAL_POWERFUL_NORMAL_FORWARD_GENERATES_EXTRA_CHANCE),
            of(301, MatchEventID.SE_TECHNICAL_SUFFERS_FROM_RAIN),
            of(302, MatchEventID.SE_POWERFUL_THRIVES_IN_RAIN),
            of(303, MatchEventID.SE_TECHNICAL_THRIVES_IN_SUN),
            of(304, MatchEventID.SE_POWERFUL_SUFFERS_FROM_SUN),
            of(305, MatchEventID.SE_QUICK_LOSES_IN_RAIN),
            of(306, MatchEventID.SE_QUICK_LOSES_IN_SUN),
            of(307, MatchEventID.SE_SUPPORT_PLAYER_BOOST_SUCCEEDED),
            of(308, MatchEventID.SE_SUPPORT_PLAYER_BOOST_FAILED_AND_ORGANIZATION_DROPPED),
            of(309, MatchEventID.SE_SUPPORT_PLAYER_BOOST_FAILED),
            of(310, MatchEventID.SE_POWERFUL_DEFENSIVE_INNER_PRESSES_CHANCE),
            of(311, MatchEventID.COUNTER_ATTACK_TRIGGERED_BY_TECHNICAL_DEFENDER),
            of(331, MatchEventID.TACTIC_TYPE_PRESSING),
            of(332, MatchEventID.TACTIC_TYPE_COUNTER_ATTACKING),
            of(333, MatchEventID.TACTIC_TYPE_ATTACK_IN_MIDDLE),
            of(334, MatchEventID.TACTIC_TYPE_ATTACK_ON_WINGS),
            of(335, MatchEventID.TACTIC_TYPE_PLAY_CREATIVELY),
            of(336, MatchEventID.TACTIC_TYPE_LONG_SHOTS),
            of(343, MatchEventID.TACTIC_ATTACK_IN_MIDDLE_USED),
            of(344, MatchEventID.TACTIC_ATTACK_ON_WINGS_USED),
            of(350, MatchEventID.PLAYER_SUBSTITUTION_TEAM_IS_BEHIND),
            of(351, MatchEventID.PLAYER_SUBSTITUTION_TEAM_IS_AHEAD),
            of(352, MatchEventID.PLAYER_SUBSTITUTION_MINUTE),
            of(360, MatchEventID.CHANGE_OF_TACTIC_TEAM_IS_BEHIND),
            of(361, MatchEventID.CHANGE_OF_TACTIC_TEAM_IS_AHEAD),
            of(362, MatchEventID.CHANGE_OF_TACTIC_MINUTE),
            of(370, MatchEventID.PLAYER_POSITION_SWAP_TEAM_IS_BEHIND),
            of(371, MatchEventID.PLAYER_POSITION_SWAP_TEAM_IS_AHEAD),
            of(372, MatchEventID.PLAYER_POSITION_SWAP_MINUTE),
            of(380, MatchEventID.MAN_MARKING_SUCCESS_SHORT_DISTANCE),
            of(381, MatchEventID.MAN_MARKING_SUCCESS_LONG_DISTANCE),
            of(382, MatchEventID.MAN_MARKED_CHANGED_FROM_SHORT_TO_LONG_DISTANCE),
            of(383, MatchEventID.MAN_MARKED_CHANGED_FROM_LONG_TO_SHORT_DISTANCE),
            of(384, MatchEventID.MAN_MARKER_PENALTY_NO_MAN_MARKED_ON_THE_FIELD),
            of(385, MatchEventID.MAN_MARKER_CHANGED_FROM_SHORT_TO_LONG_DISTANCE),
            of(386, MatchEventID.MAN_MARKER_CHANGED_FROM_LONG_TO_SHORT_DISTANCE),
            of(387, MatchEventID.MAN_MARKER_PENALTY_MAN_MARKED_NOT_IN_MARKING_POSITION),
            of(388, MatchEventID.MAN_MARKER_PENALTY_MAN_MARKER_NOT_IN_MARKING_POSITION),
            of(389, MatchEventID.MAN_MARKER_PENALTY_NO_MAN_MARKED_IN_OPPONENT_TEAM),
            of(390, MatchEventID.RAINY_WEATHER_MANY_PLAYERS_AFFECTED),
            of(391, MatchEventID.SUNNY_WEATHER_MANY_PLAYERS_AFFECTED),
            of(401, MatchEventID.INJURY_KNEE_LEFT),
            of(402, MatchEventID.INJURY_KNEE_RIGHT),
            of(403, MatchEventID.INJURY_THIGH_LEFT),
            of(404, MatchEventID.INJURY_THIGH_RIGHT),
            of(405, MatchEventID.INJURY_FOOT_LEFT),
            of(406, MatchEventID.INJURY_FOOT_RIGHT),
            of(407, MatchEventID.INJURY_ANKLE_LEFT),
            of(408, MatchEventID.INJURY_ANKLE_RIGHT),
            of(409, MatchEventID.INJURY_CALF_LEFT),
            of(410, MatchEventID.INJURY_CALF_RIGHT),
            of(411, MatchEventID.INJURY_GROIN_LEFT),
            of(412, MatchEventID.INJURY_GROIN_RIGHT),
            of(413, MatchEventID.INJURY_COLLARBONE),
            of(414, MatchEventID.INJURY_BACK),
            of(415, MatchEventID.INJURY_HAND_LEFT),
            of(416, MatchEventID.INJURY_HAND_RIGHT),
            of(417, MatchEventID.INJURY_ARM_LEFT),
            of(418, MatchEventID.INJURY_ARM_RIGHT),
            of(419, MatchEventID.INJURY_SHOULDER_LEFT),
            of(420, MatchEventID.INJURY_SHOULDER_RIGHT),
            of(421, MatchEventID.INJURY_RIB),
            of(422, MatchEventID.INJURY_HEAD),
            of(423, MatchEventID.INJURED_BY_FOUL),
            of(424, MatchEventID.INJURED_PLAYER_REPLACED),
            of(425, MatchEventID.NO_REPLACEMENT_FOR_INJURED_PLAYER),
            of(426, MatchEventID.FIELD_PLAYER_HAS_TO_TAKE_INJURED_KEEPERS_PLACE),
            of(427, MatchEventID.PLAYER_INJURED_WAS_REGAINER_SO_GOT_BRUISED_INSTEAD),
            of(450, MatchEventID.PLAYER_GOT_THIRD_YELLOW_CARD_MISSES_NEXT_MATCH),
            of(451, MatchEventID.WITH_THIS_STANDING_TEAM_X_WILL_RELEGATE_TO_CUP_Y),
            of(452, MatchEventID.PLAYER_CURRENT_TEAM_MATCHES_100S_ANNIVERSARY),
            of(453, MatchEventID.PLAYER_POSSIBLY_THE_LAST_GAME_IN_THIS_TEAM),
            of(454, MatchEventID.DOCTOR_REPORT_OF_INJURY_LENGTH),
            of(455, MatchEventID.NEW_STAR_PLAYER_OF_THE_TEAM),
            of(456, MatchEventID.PLAYER_CAREER_GOALS_MULTIPLE_OF_50),
            of(457, MatchEventID.PLAYER_LEAGUE_GOALS_THIS_SEASON),
            of(458, MatchEventID.PLAYER_CUP_GOALS_THIS_SEASON),
            of(459, MatchEventID.BENCH_PLAYER_WARMING_UP),
            of(460, MatchEventID.FANS_SHOCKED_BY_LOSING),
            of(461, MatchEventID.FANS_UPSET_BY_LOSING),
            of(462, MatchEventID.FANS_SURPRISED_BY_WINNING),
            of(463, MatchEventID.FANS_EXCITED_BY_WINNING),
            of(464, MatchEventID.EXACT_NUMBER_OF_SPECTATORS),
            of(465, MatchEventID.TEAM_SHOULD_WIN_MATCH_TO_SECURE_WINNING_THE_LEAGUE),
            of(466, MatchEventID.TEAM_SHOULD_WIN_MATCH_TO_HAVE_CHANCE_OF_WINNING_LEAGUE),
            of(467, MatchEventID.THE_WINNER_OF_THIS_MATCH_IF_THERE_IS_ONE_CAN_HAVE_A_CHANCE_OF_WINNING_THE_LEAGUE),
            of(468, MatchEventID.TEAM_SHOULD_WIN_MATCH_TO_MAKE_SURE_THEY_DONT_DEMOTE),
            of(469, MatchEventID.TEAM_SHOULD_WIN_MATCH_TO_HAVE_A_CHANCE_OF_NOT_DEMOTING),
            of(470, MatchEventID.THE_LOSER_OF_THIS_MATCH_WILL_DEMOTE),
            of(471, MatchEventID.HOMETEAM_OR_AWAYTEAM_HAS_MOST_POSSESSION_IN_BEGINNING_OF_MATCH),
            of(472, MatchEventID.EQUAL_POSSESSION_IN_BEGINNING_OF_MATCH),
            of(473, MatchEventID.CAREER_ENDING_INJURY),
            of(474, MatchEventID.POSSESSION_SHIFTED),
            of(475, MatchEventID.LOW_ATTENDANCE_BECAUSE_OF_FAN_MOOD),
            of(476, MatchEventID.EXTRA_SECURITY_BECAUSE_OF_FAN_MOOD),
            of(477, MatchEventID.BOTH_TEAMS_FANS_ARE_ANGRY),
            of(478, MatchEventID.TEAM_WILL_HAVE_BEST_CUP_RUN_IF_WIN),
            of(479, MatchEventID.BOTH_TEAMS_COULD_HAVE_BEST_CUP_RUN_IF_WIN_COMPETING),
            of(480, MatchEventID.CURRENT_ROUND_IS_TEAMS_BEST_CUP_RUN),
            of(481, MatchEventID.NEW_FORMATION_TODAY),
            of(482, MatchEventID.TEAMS_USING_THE_SAME_STYLE_OF_PLAY),
            of(483, MatchEventID.TEAMS_USING_DIFFERENT_STYLES_OF_PLAY),
            of(484, MatchEventID.ONE_TEAMS_STYLE_OF_PLAY),
            of(485, MatchEventID.TEAM_OF_OLDIES),
            of(486, MatchEventID.TEAM_IS_AGGRESSIVE),
            of(487, MatchEventID.TEAM_HAS_ONLY_HOMEGROWN_PLAYERS),
            of(488, MatchEventID.TEAM_HAS_ALL_PLAYERS_FROM_SAME_COUNTRY),
            of(489, MatchEventID.COMEBACK_AFTER_A_LONG_INJURY),
            of(490, MatchEventID.PREVIOUS_MATCH_CUP_SIMILAR_OUTCOME),
            of(491, MatchEventID.PREVIOUS_MATCH_CUP_DIFFERENT_OUTCOME),
            of(492, MatchEventID.PREVIOUS_MATCH_LEAGUE_SIMILAR_OUTCOME),
            of(493, MatchEventID.PREVIOUS_MATCH_LEAGUE_DIFFERENT_OUTCOME),
            of(494, MatchEventID.TEAM_HAS_THE_BALL_BUT_IS_NOT_ATTACKING),
            of(495, MatchEventID.TEAM_HAS_THE_BALL_AND_HAS_STARTED_ATTACKING),
            of(496, MatchEventID.TEAM_IS_STILL_IN_THE_CUP_FOR_LEAGUE_MATCHES),
            of(497, MatchEventID.BOTH_TEAMS_ARE_STILL_IN_THE_CUP_FOR_LEAGUE_MATCHES),
            of(498, MatchEventID.TEAM_IS_LOOKING_TIRED_LOW_AVG_STAMINA),
            of(500, MatchEventID.BOTH_TEAMS_WALKOVER),
            of(501, MatchEventID.HOME_TEAM_WALKOVER),
            of(502, MatchEventID.AWAY_TEAM_WALKOVER),
            of(503, MatchEventID.BOTH_TEAMS_BREAK_GAME_2_PLAYERS_REMAINING),
            of(504, MatchEventID.HOME_TEAM_BREAKS_GAME_2_PLAYERS_REMAINING),
            of(505, MatchEventID.AWAY_TEAM_BREAKS_GAME_2_PLAYERS_REMAINING),
            of(510, MatchEventID.YELLOW_CARD_NASTY_PLAY),
            of(511, MatchEventID.YELLOW_CARD_CHEATING),
            of(512, MatchEventID.RED_CARD_2ND_WARNING_NASTY_PLAY),
            of(513, MatchEventID.RED_CARD_2ND_WARNING_CHEATING),
            of(514, MatchEventID.RED_CARD_WITHOUT_WARNING),
            of(596, MatchEventID.EXTRA_TIME_STARTED_THIRD_HALF),
            of(597, MatchEventID.SECOND_HALF_STARTED),
            of(598, MatchEventID.MATCH_STARTED),
            of(599, MatchEventID.MATCH_FINISHED),
            of(601, MatchEventID.CONGRATULATIONS_TO_THE_WINNER),
            of(602, MatchEventID.WINNER_ADVANCES_TO_NEXT_CUP_ROUND_NO_RELEGATION_CUP_FOR_LOSER),
            of(603, MatchEventID.WINNER_ADVANCES_TO_NEXT_CUP_ROUND_AND_LOSER_RELEGATES_TO_CUP_X),
            of(604, MatchEventID.MATCH_ENDED_IN_A_TIE),
            of(605, MatchEventID.END_OF_MATCH_CONGRATULATIONS_TEAM_WON_THE_LEAGUE),
            of(606, MatchEventID.END_OF_MATCH_SAD_THAT_TEAM_WILL_DEMOTE_DIRECTLY),
            of(650, MatchEventID.HATTRICK_ANNIVERSARY),
            of(651, MatchEventID.TEAM_ANNIVERSARY),
            of(700, MatchEventID.EVENTOMATIC_MANAGER_TAUNTS_OPPONENT),
            of(701, MatchEventID.EVENTOMATIC_MANAGER_PRAISES_OPPONENT),
            of(702, MatchEventID.EVENTOMATIC_MANAGER_ASKS_FANS_FOR_SUPPORT),
            of(703, MatchEventID.EVENTOMATIC_MANAGER_EXPECTS_GREAT_SHOW),
            of(704, MatchEventID.EVENTOMATIC_MANAGER_HONOURS_CLUB_LEGACY),
            of(800, MatchEventID.STAR_PLAYER_MISSED_MATCH_BECAUSE_OF_RED_CARD),
            of(801, MatchEventID.STAR_PLAYER_MISSED_MATCH_BECAUSE_OF_INJURY),
            of(802, MatchEventID.TEAM_IS_ON_WINNING_STREAK),
            of(803, MatchEventID.BOTH_TEAMS_ARE_ON_WINNING_STREAK),
            of(804, MatchEventID.TEAM_WILL_BREAK_WINNING_STREAK),
            of(805, MatchEventID.WEAKEST_TEAM_HTRATING_IS_WINNING),
            of(806, MatchEventID.POSSESSION_SHIFT_BECAUSE_OF_RED_CARD),
            of(807, MatchEventID.POSSESSION_SHIFT_BECAUSE_OF_SUBSTITUTION_LOST),
            of(808, MatchEventID.POSSESSION_SHIFT_BECAUSE_OF_SUBSTITUTION_GAINED),
            of(809, MatchEventID.POSSESSION_SHIFT_OTHER_REASON),
            of(810, MatchEventID.PREVIOUS_MATCH_WINNER),
            of(811, MatchEventID.PREVIOUS_MATCH_WAS_A_TIE),
            of(812, MatchEventID.PLAYER_BIRTHDAY),
            of(813, MatchEventID.NEW_MATCH_KIT),
            of(814, MatchEventID.TEAM_UNDERPERFORMING_COMPARED_TO_LAST_LEAGUE_MATCH_HT_RATING),
            of(815, MatchEventID.TEAM_OVERPERFORMING_COMPARED_TO_LAST_LEAGUE_MATCH_HT_RATING),
            of(816, MatchEventID.POSSESSION_SHIFT_BECAUSE_OF_TEAM_CONFUSION),
            of(817, MatchEventID.POSSESSION_SHIFT_BECAUSE_OF_TEAM_NERVES),
            of(818, MatchEventID.BROTHERS_PLAY_FOR_SAME_TEAM),
            of(819, MatchEventID.FATHER_SON_PLAY_FOR_SAME_TEAM),
            of(820, MatchEventID.FAMILY_MEMBERS_PLAY_AGAINST_EACH_OTHER),
            of(821, MatchEventID.Family_members_assist_goal),
            of(822, MatchEventID.FAMILY_MEMBERS_FACING_EACH_OTHER_IN_A_PENALTY),
            of(880, MatchEventID.ASSIST_END_TO_A_GOAL)
        );
    }

    @ParameterizedTest
    @MethodSource
    void MatchEventID_fromMatchEventID(int id, MatchEventID expected) {
        assertThat(MatchEventID.fromMatchEventID(id)).isEqualTo(expected);
    }

    private static Stream<Arguments> MatchEventID_fromMatchEventID_is_UNKNOWN_MATCHEVENT() {
        return Stream.of(
                IntStream.rangeClosed(-1, 18).mapToObj(Arguments::of),
                Stream.of(Arguments.of(29)),
                Stream.of(Arguments.of(34)),
                IntStream.rangeClosed(43, 44).mapToObj(Arguments::of),
                IntStream.rangeClosed(48, 54).mapToObj(Arguments::of),
                Stream.of(Arguments.of(74)),
                IntStream.rangeClosed(77, 79).mapToObj(Arguments::of),
                IntStream.rangeClosed(82, 89).mapToObj(Arguments::of),
                IntStream.rangeClosed(98, 99).mapToObj(Arguments::of),
                IntStream.rangeClosed(126, 129).mapToObj(Arguments::of),
                IntStream.rangeClosed(144, 149).mapToObj(Arguments::of),
                IntStream.rangeClosed(155, 159).mapToObj(Arguments::of),
                IntStream.rangeClosed(165, 169).mapToObj(Arguments::of),
                IntStream.rangeClosed(175, 179).mapToObj(Arguments::of),
                IntStream.rangeClosed(188, 189).mapToObj(Arguments::of),
                IntStream.rangeClosed(191, 199).mapToObj(Arguments::of),
                IntStream.rangeClosed(226, 229).mapToObj(Arguments::of),
                Stream.of(Arguments.of(238)),
                IntStream.rangeClosed(244, 249).mapToObj(Arguments::of),
                IntStream.rangeClosed(255, 259).mapToObj(Arguments::of),
                IntStream.rangeClosed(265, 269).mapToObj(Arguments::of),
                IntStream.rangeClosed(275, 279).mapToObj(Arguments::of),
                IntStream.rangeClosed(291, 300).mapToObj(Arguments::of),
                IntStream.rangeClosed(312, 330).mapToObj(Arguments::of),
                IntStream.rangeClosed(337, 342).mapToObj(Arguments::of),
                IntStream.rangeClosed(345, 349).mapToObj(Arguments::of),
                IntStream.rangeClosed(353, 359).mapToObj(Arguments::of),
                IntStream.rangeClosed(363, 369).mapToObj(Arguments::of),
                IntStream.rangeClosed(373, 379).mapToObj(Arguments::of),
                IntStream.rangeClosed(392, 400).mapToObj(Arguments::of),
                IntStream.rangeClosed(428, 449).mapToObj(Arguments::of),
                Stream.of(Arguments.of(499)),
                IntStream.rangeClosed(506, 509).mapToObj(Arguments::of),
                IntStream.rangeClosed(515, 595).mapToObj(Arguments::of),
                Stream.of(Arguments.of(600)),
                IntStream.rangeClosed(607, 649).mapToObj(Arguments::of),
                IntStream.rangeClosed(652, 699).mapToObj(Arguments::of),
                IntStream.rangeClosed(705, 799).mapToObj(Arguments::of),
                IntStream.rangeClosed(823, 879).mapToObj(Arguments::of),
                IntStream.rangeClosed(881, 1000).mapToObj(Arguments::of)
            )
            .flatMap(i -> i);
    }

    @ParameterizedTest
    @MethodSource
    void MatchEventID_fromMatchEventID_is_UNKNOWN_MATCHEVENT(int id) {
        assertThat(MatchEventID.fromMatchEventID(id)).isEqualTo(MatchEventID.UNKNOWN_MATCHEVENT);
    }

    private static Stream<Arguments> MatchEventID_whiteListFromBlackList() {
        final var blackList = MatchEventID_fromMatchEventID_is_UNKNOWN_MATCHEVENT()
            .map(arg -> (Integer) arg.get()[0])
            .collect(Collectors.toSet());
        return IntStream.rangeClosed(-1, 1000)
            .filter(id -> !blackList.contains(id))
            .boxed()
            .collect(Collectors.toSet())
            .stream()
            .map(Arguments::of);
    }


    @ParameterizedTest
    @MethodSource("MatchEventID_whiteListFromBlackList")
    void MatchEventID_fromMatchEventID_whiteListIsCompleteDueToCompleteBlackList(int whiteListIdFromBlackList) {
        final var matchEventID = MatchEventID.fromMatchEventID(whiteListIdFromBlackList);
        assertThat(matchEventID).isNotEqualTo(MatchEventID.UNKNOWN_MATCHEVENT);
    }

    private static Stream<Arguments> MatchPartId_fromMatchPartId() {
        return Stream.of(
            of(-1, null),
            of(0, MatchPartId.BEFORE_THE_MATCH_STARTED),
            of(1, MatchPartId.FIRST_HALF),
            of(2, MatchPartId.SECOND_HALF),
            of(3, MatchPartId.OVERTIME),
            of(4, MatchPartId.PENALTY_CONTEST),
            of(5, null)
        );
    }

    @ParameterizedTest
    @MethodSource
    void MatchPartId_fromMatchPartId(int id, MatchPartId expected) {
        assertThat(MatchPartId.fromMatchPartId(id)).isEqualTo(expected);
    }

    private static Stream<Arguments> MatchPartId_toInteger() {
        return Stream.concat(Arrays.stream(MatchPartId.values()), Stream.of((MatchPartId) null))
            .map(Arguments::of);
    }

    @ParameterizedTest
    @MethodSource
    void MatchPartId_toInteger(MatchPartId matchPartId) {
        final var expected = Optional.ofNullable(matchPartId).map(MatchPartId::getValue).orElse(null);
        assertThat(MatchPartId.toInteger(matchPartId)).isEqualTo(expected);
    }
}
